### ISSUE TITLE
Links to the project repo are broken

### ISSUE THREAD

**Issue by prantlf** [lite-xl/website-archive#1]
It is probably still work in progress, so this is more of a reminder for you ;-)

Links that point to the `lite-xl` project repo are broken, because that repo has not been moved to the `lite-xl` organisation and resides on https://github.com/franko/lite-xl. For example: Wiki and Issue Tracker on https://lite-xl.github.io/. Until the repo is moved, you my want to point the links to the existing one, or speed up the move.

**Comment by redtide** [comment]
No need to hurry, I'll change the links.

**Comment by redtide** [comment]
Done, should be OK now, let me know if I missed something.

**Comment by prantlf** [comment]
It works well, thank you! Great job!

**Comment by redtide** [comment]
Thank you! 😃
