### ISSUE TITLE
Normalize keymap data

### ISSUE THREAD

**Issue by takase1121** [lite-xl/website-archive#11]
There are duplicate entries in the keymap:
![image](https://user-images.githubusercontent.com/20792268/132153672-75aab21a-a702-4d99-8b4f-81983fe2a625.png)

And there are also duplicates that can be put into 1 entry with combos:
![image](https://user-images.githubusercontent.com/20792268/132153713-8b1fec52-7d17-42d5-932f-d2c993cf8b00.png)

Ideally it should look like this:
![image](https://user-images.githubusercontent.com/20792268/132153768-c21fd769-c337-42a9-97ff-072f872e452f.png)

**Comment by redtide** [comment]
I'm still thinking about auto generate the keymap json file in some way so I have no idea about this, in this case could be grouped inside the parser (in the json generator or in the site) if any. Thoughts?

**Comment by takase1121** [comment]
I'm certainly thinking of that. I thought you had a script for it already.
If you don't, I don't mind writing one.

**Comment by redtide** [comment]
Nope, was an idea discussed together with the plugin context IIRC but haven't done nothing yet except the current hypothetical result of how the json should be and its simple parser for the site, so go ahead

**Comment by redtide** [comment]
I notice only now that I created #4 for that purpose but closed because I realized that in my case contributing on this project (not the site, the application) is a waste of my time and energy.
