### ISSUE TITLE
Make a theme creation documentation

### ISSUE THREAD

**Issue by dheison0** [lite-xl/website-archive#20]
I want to improve some themes of lite-xl but I have some questions:

  - What's `background2`, `background3`, `line_number2`, `dim`, `accent` and `scrollbar2` used by the theme files?
  - What's `keyword2` used by the syntax highlight?

I suggest to rename it and update all themes

**Comment by Guldoman** [comment]
A bunch of those are described here: https://github.com/lite-xl/lite-xl/blob/8ce1ecb8973ae067adc4f3d35bb0d9aff0669d97/data/core/style.lua

* `background2`: secondary background color for the tabs bar, the `TreeView`, the status bar, the toolbar
* `background3`: is used in things like the autocomplete, the status bar tooltips (2.1 only I think), the command palette suggestions background
* `line_number2`: is the color of the line number when the cursor is in that line
* `dim`: tabs title, tabs separator, toolbar icons, some elements in the status bar, the shortcuts in the command palette suggestion
* `accent`: the text of selected suggestions in the command palette, the "unsaved changes" icon in the status bar, project search hovered results
* `scrollbar2`: hovered scrollbar thumb

* `keyword2`: usually used for predefined types, like `int`, `float`, `double`, `char` in C

To check where a style is used I'd suggest changing it to a vibrant color in your user module and restarting the editor.
For example:
```lua
style.accent = { 255, 0, 0, 255 } -- RGBA
```

**Comment by dheison0** [comment]
A web page teaching what each such value does is better than opening a file in the editor to see the comments describing each one, I'll close this issue and you decide whether or not to create the page

**Comment by takase1121** [comment]
I would like to emphasize that this is a open source project collaboratively developed by the community. We're working towards improving documentation in general but do expect rough edges and missing content.

You don't have to be condescending. The website is written in markdown and hosted here. Its not too hard to write markdown and you're more than welcome to contribute to it if you feel like it.

**Comment by dheison0** [comment]
Ok, I will try to do this, I don't speak english, so, don't expect a good text, I will try to translate the website to brazilian portuguese too

**Comment by dheison0** [comment]
I have created a PR for the page that I was created, check here #21
