### ISSUE TITLE
Local Build Quick-start Guide didn't work

### ISSUE THREAD

**Issue by bjornbm** [lite-xl/website-archive#3]
The “Local Build Quick-start Guide” in the [README](https://github.com/lite-xl/lite-xl.github.io/blob/master/README.md) didn't work for me (on macOS). I know next to nothing about Ruby ecosystem, but in the end I believe the process that worked was:

1.  Install `ruby` and `yarn`. I installed these with homebrew and ended up with Ruby 3.0.1.

2.  Modify the [Gemfile](https://github.com/lite-xl/lite-xl.github.io/blob/master/Gemfile):
    - Comment out the `ruby "2.7.1"` to allow for 3.0.1.
    - Add `gem "webrick"` (https://github.com/jekyll/jekyll/issues/8523).

3.  `site run --install`. On subsequent runs, the `--install` isn't required.

I propose that someone more familiar with the tooling make appropriate updates (which may be different than those above) to the Gemfile and README.

**Comment by redtide** [comment]
I personally force the use of a specific ruby version (using [RVM]) to match GitHub Pages [versions] after some compatibility issue in the past. Anyway thanks for this, I'll try to find some decent solution when I'll get in my mac vm.

[versions]: https://pages.github.com/versions/
[RVM]: https://rvm.io/

**Comment by bjornbm** [comment]
Yeah, I realized it can be done with appropriate sandboxing, but it would have been nice if the instructions were more complete for us clueless folks. I see the point of wanting to pin versions to match Github Pages.

**Comment by redtide** [comment]
TBH I did some websites similar to this for other projects but it's the first time I get some feedback, not much people tries jekyll sites locally. OTOH I was the one to point you here for the keymap issue and forgot about macOS differences, my bad.

**Comment by bjornbm** [comment]
No problem. I don't really think the problems I ran into were macOS-specific. I mean, the problem was that I didn't know how to use RVM instead of the ruby installation my “package manager” (homebrew) provided. I imagine the situation would be the same on any platform.

**Comment by redtide** [comment]
I'll look into this when I'll have time to test on macOS a change to permit to use a different ruby version with a simple "[if not]" condition in the Gemfile when using it. It will probably ends with an initial macOS section in the README with what you described in your OP.
Or if you have time I wouldn't mind if you could do it in a PR meanwhile, as you prefer.

[if not]: https://stackoverflow.com/questions/46587991/how-can-i-conditionally-load-a-local-gem-in-my-rails-4-2-gemfile/46588554#46588554

**Comment by bjornbm** [comment]
>  Or if you have time I wouldn't mind if you could do it in a PR meanwhile, as you prefer.

I think it is better that you do the correct thing with the Gemfile etc, rather than I try to muddle through it. But I propsed a stopgap README update.

**Comment by redtide** [comment]
I've made some [work][1] on master and added some information on the [wiki][2], the installation now should be straightforward, though I guess it's not perfect yet, I'll need to add some documentation for the commands to use later.

[1]: https://github.com/lite-xl/lite-xl.github.io/commit/02614bcf177a3967cfa028e7051c793a312def20
[2]: https://github.com/lite-xl/lite-xl.github.io/wiki/Site-Install-Locally

**Comment by redtide** [comment]
Closing, please reopen if this is still a problem.
